### ISSUE TITLE
经常遇到 'ascii' codec can't encode characters 错误

### ISSUE THREAD

**Issue by chinuno-usami** [fuckbilibili/Bilibili-Silver-Grab#2]
``` 
错误！ 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
Traceback (most recent call last):
  File "autograb.py", line 259, in <module>
    main(headers)
  File "autograb.py", line 209, in main
    award, nowsilver = get_award(headers, answer)
  File "autograb.py", line 123, in get_award
    print(a['msg'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
```
如上信息。python版本2.7.10.
每次领取的时候50%概率遇到这个问题，然后又重新计时
然而也看不到b站返回的错误信息，不知道是什么错误

**Comment by hanbang-wang** [comment]
噫 应该是编码问题 试试在后面加个.encode(utf-8)

**Comment by chinuno-usami** [comment]
嗯。似乎是这个问题
这次输出的验证码错误的信息
原来一直以为python2.x可以直接print的unicode
因为try在true循环里面所以抛出异常后直接回到循环里面进行下一次了
解决了。close了吧
