### ISSUE TITLE
这几天不能用了。

### ISSUE THREAD

**Issue by chinuno-usami** [fuckbilibili/Bilibili-Silver-Grab#3]
看了看log这几天都是失败的。
出了像下面这样的错误..这是用的人太多ocr的api使用次数爆了？
> 还剩下1分钟……
开始领取！
错误！ 'retData'
Traceback (most recent call last):
  File "autograb.py", line 259, in <module>
    main(headers)
  File "autograb.py", line 203, in main
    answer = captcha_wrapper(headers)
  File "autograb.py", line 156, in captcha_wrapper
    captcha_text = image_link_ocr(captcha_link).encode('utf-8')
  File "autograb.py", line 99, in image_link_ocr
    return res['retData'][0]['word']
KeyError: 'retData'
预计下一次领取需要3分钟，可以领取30个银瓜子
还剩下3分钟……
还剩下2分钟……
还剩下1分钟……
错误！ No JSON object could be decoded
Traceback (most recent call last):
  File "autograb.py", line 259, in <module>
    main(headers)
  File "autograb.py", line 197, in main
    while not award_requests(headers):
  File "autograb.py", line 132, in award_requests
    a = loads(response.content.decode('utf-8'))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
预计下一次领取需要3分钟，可以领取30个银瓜子

**Comment by hanbang-wang** [comment]
是的，看起来是ocr爆了，不知道是次数上限还是百度的问题，现在正在寻找另外的ocr提供商

**Comment by chinuno-usami** [comment]
<2015-12-18 五>: 个人免费版服务已下线

是百毒ocr的免费版下线了。。

**Comment by hanbang-wang** [comment]
准备换用pytesseract了……
